apiVersion: v1
kind: Service
metadata:
  name: mo-agent-service
  labels:
    app-name: mo-agent
spec:
  type: {{ .Values.moAgent.service.type }}
  selector:
    app: mo-agent
  ports:
    - name: http
      port: {{ .Values.moAgent.service.port }}
      targetPort: {{ .Values.moAgent.service.targetPort }}
      protocol: TCP
    # - name: https
    #   port: {{ .Values.moAgent.service.port }}
    #   targetPort: {{ .Values.moAgent.service.targetPort }}
    #   protocol: TCP